const notes = Array.from({ length: 62 }, (_, i) => {
  const categories = ["pink", "blue", "yellow"];
  const category = categories[i % 3];
  const notes = [
  { id: 1, category: "pink", message: "I love the way you speak your mind, and you’re not afraid to speak about the things that truly matter." },
  { id: 2, category: "blue", message: "I love how you can effortlessly speak about topics no one else would dare ever touch." },
  { id: 3, category: "yellow", message: "I love how we can both talk endlessly on such topics without overpowering each other." },
  { id: 4, category: "pink", message: "I love your curiosity, and how you pose questions about the world. Or, how you always ask me questions lingering in your mind, I’ll never not be able to always answer them, even as much as I would say I don’t want to answer, for you, there isn’t anything I’m not willing to give or share." },
  { id: 5, category: "blue", message: "I love your passion and how it radiates off of you and how it has a ripple effect in a way that being with you has also made me want to be more passionate about everything." },
  { id: 6, category: "yellow", message: "I love your love for social justice and being able to make a change in the world, no matter how small. As much as you say all you do is complain about it, anyone can tell how much love you have for the cause and the lengths you would go to support and make a difference" },
  { id: 7, category: "pink", message: "I love your caring nature, just the way you interact with Naia and how you are with your sister and friends, you embody all the characteristics for a caring and nurturing owner, older sister, and friend. It’s lovely to see with my own very eyes, everyone surrounded by you is truly lucky" },
  { id: 8, category: "blue", message: "I love your insatiable thirst for knowledge in the arts, music, language, literature, education, social justice, everything, I love how you just wanna learn it all and bask in it all. Truly in that regard I don’t know if I wanna be you or be lucky enough to be with you so that you can share to me all that you know." },
  { id: 9, category: "yellow", message: "I love your drive and motivation to power through it all, my love I have never seen anyone WILLINGLY do school for 12 months straight, in that regard you truly stand solo. I could never be more proud, to the point I’d just use it to brag about you all the time. I have a smart ass fucking girlfriend who’s so determined she spent an entire year dedicated to school. Infinite amount of bragging rights." },
  { id: 10, category: "pink", message: "I love how you always think things through, and are always 100% sure on something before making the decision." },
  { id: 11, category: "blue", message: "I love your willingness and the way you’re always open to trying new things. Even when they are entirely out of your comfort zone, you’re willing to make the leap, and in return it makes my heart take a leap because of how much in awe I am." },
  { id: 12, category: "yellow", message: "I love that most of the time the things you aren’t willing to do but do anyway are through my annoying suggestions and persist rants. I love your hobbies and how they reflect so well on your personality and passions." },
  { id: 13, category: "pink", message: "I love your movie knowledge, even though you so lied about not being into movies as much as I am, because you are so much more into movies than I am." },
  { id: 14, category: "blue", message: "I love your music knowledge and the plethora of music you listen to and enjoy." },
  { id: 15, category: "yellow", message: "I love your book knowledge and how every story has resonated with you in one way or another and how you can have so much opinions about each one critiquing, loving, searching, just from reading your reviews, you always have something to share." },
  { id: 16, category: "pink", message: "I love that, it shows that you truly honed in on the piece of literature and actually gave it your two cents. I swear no one else does that anymore, and you do it so effortlessly. Baby, what I would give to walk in through the library that you keep in your head." },
  { id: 17, category: "blue", message: "I also love your lack of knowledge, your lack of knowledge on sports makes it so that I can teach you everything there is to know about all the sports I play, watch, or just in general enjoy. Granted I’d probably bore you to death with it all, but I love being able to share all of it with you." },
  { id: 18, category: "yellow", message: "I love your lack of knowledge for video games, whether they’re classical retro games or up-to-date modern games. Gives me the opportunity to share and show you the games I enjoy or are out there in general. Never have I thought I would be playing a high school musical video game with my girlfriend or a hell’s kitchen one for that matter." },
  { id: 19, category: "pink", message: "I love your lack of knowledge for technology or at least the internal states of it, so that I can share with you a building curiosity//hobby of mine that mixes all the parts I take interest in." },
  { id: 20, category: "blue", message: "I love how you can always remember all the silly little things I say. As if they were the back of your hand, it’s mind-blowing to say the least." },
  { id: 21, category: "yellow", message: "I love your perfect sense of humour and how it matches mine so perfectly well as if they were two connecting puzzle pieces." },
  { id: 22, category: "pink", message: "I love the way you wanna approach any dog you come across." },
  { id: 23, category: "blue", message: "I love the way you always give me your time, even when sleep is knocking down your door." },
  { id: 24, category: "yellow", message: "I love your temperature, more often than not you are always the opposite temperature as me, as if when we’re apart we grow cold and are on polar opposite sides from one another. Then it is only once we get together where we can share and meet in the middle for the perfect warmth mix. Whether I start cold, and your heating up a flame, or you’re cold and I can warm you up, it seems rather perfect as much things are for us." },
  { id: 25, category: "pink", message: "I love your style and how every time I am in absolute distraught at how amazingly gorgeous you make everything look, and you yourself is the cherry on top." },
  { id: 26, category: "blue", message: "I love the way that even before we got together we would match unplanned, and show just how much of lingering connection we had." },
  { id: 27, category: "yellow", message: "I love your thoughtful nature and how you always make sure to be observant of those around you." },
  { id: 28, category: "pink", message: "I love your desire to grow, not only as an individual but also in all the roles you shoulder, as a sister, friend, daughter, student, or a fighter. You are determined to put up a winning fight to grow." },
  { id: 29, category: "blue", message: "I love the way you show your support by being there for someone and giving them your time." },
  { id: 30, category: "yellow", message: "I love your facial expressions, when you’re confused, surprised, happy, pouting, plotting, each one, as much as I think I know and can read always manage to keep me second guessing just because of how each one is so unique and special." },
  { id: 31, category: "pink", message: "Speaking of special, I love how you make every single moment with you special in their own way." },
  { id: 32, category: "blue", message: "I love how being with you sounds so peaceful, divine, chaotically beautiful and imaginatively magical all at the same time." },
  { id: 33, category: "yellow", message: "I love how you’re so accepting and open to anything I make you or give you, edible, wearable, or collectible." },
  { id: 34, category: "pink", message: "I love how mucnhable you are, you’d be the perfect delicacy, the perfect meal, the perfect dessert, the perfect snack, everything you’re just so scrumptious." },
  { id: 35, category: "blue", message: "I love your love for peanut butter and how it’s your favourite." },
  { id: 36, category: "yellow", message: "In general I love your love for sweets and how much of a sweet tooth you have. Though I don’t really have sweet cravings apart from ice cream or cold delicacy, I wanna be able to share as much sweets with you as possible. Learn all the sweets you love and enjoy." },
  { id: 37, category: "pink", message: "I love your love for fireworks and how adorable you sound when you talk about them." },
  { id: 38, category: "blue", message: "I love your love for dogs and how you think they’re the most precious animals in the world, and honestly I agree so bad. I love how we can share our love for them." },
  { id: 39, category: "yellow", message: "I love how in general we share our love for animals, and how we can go one talking about them forever." },
  { id: 40, category: "pink", message: "I love your love for the rain, and how now whenever it rains, you are the first thing I think about." },
  { id: 41, category: "blue", message: "I love how you share your sunsets and moons with me, how when you love something, you wanna share it with me." },
  { id: 42, category: "yellow", message: "I love how we can just be watching clouds all day and still never get bored or tired of it. " },
  { id: 43, category: "pink", message: "I love how even an entire full day with still always feel as short as five minutes and as much as I think we have a long time together, it actually is never enough, and it can never be enough. " },
  { id: 44, category: "blue", message: "I love how you match my energy even when it’s the most unhinged and chaotic behaviour ever. If it were anyone else they’d for sure be running for the hills, but you never do, I love that." },
  { id: 45, category: "yellow", message: "I love how you match my affection, even when out in public, how it all just feels so natural with you and warm." },
  { id: 46, category: "pink", message: "I love how safe and secure you feel. You never fail to make me feel secure, in public, in private, every sacred moment feels so cherished. Physically you feel like a bubble wrap." },
  { id: 47, category: "blue", message: "I love that even if we’re not conversing, we can just exist in silence and it’s still the most comforting feeling in the world." },
  { id: 48, category: "yellow", message: "I love your way of assurance, as much as I persist that it could be worse, you’ll always be there to tell me it could in fact be better. " },
  { id: 49, category: "pink", message: "I love the way you lie about my height and tell everyone I’m shorter than you, it’s cute, but so heavily inaccurate. You’re still spreading false information." },
  { id: 50, category: "blue", message: "I love your height and how we’re the SAME height and how I can be face to face with you without breaking my neck." },
  { id: 51, category: "yellow", message: "I love your sincerity and honesty. How you’re always unapologetically yourself and you aren’t afraid to show it. From your crude language to your full bluntness, baby you are amazing, and I love that." },
  { id: 52, category: "pink", message: "I love how we share similar physiques and how each part of you matches each part of me." },
  { id: 53, category: "blue", message: "I love your hair for the way they shine and fall so gracefully over your shoulders. The way they’re so soft and anytime I caress them I just want to trace every single piece. " },
  { id: 54, category: "yellow", message: "I love your attentive ears and how they’re always willing to give me their full function. Even when I may just be talking pure nonsense and talking just to talk, they’ll always be listening." },
  { id: 55, category: "pink", message: "I love your eyes and the way they glimmer at everything. How they’re such a deep mesmerizing brown, from your eyelids to the centre of your pupil, every detail so intricate and delicate. The way they always seem to be observing their surroundings and paying attention to the littlest of details. Each time tracing my movements, and anticipating everything. How they hold so much stories and meaning behind them, how I can stare at them forever and never get bored, so much I just wanna stare forever. The way the sunlight reflects so very perfectly upon them, to the point that they’re a blazing hazel, and it’s the perfect amplification. How I can look into them and see my reflection so clear and visible. " },
  { id: 56, category: "blue", message: "I love your button nose, so cute and munchable. " },
  { id: 57, category: "yellow", message: "I love your cheeks, how they’re so punchable, munchable, and scrumptious looking. How they’re so BIG, SOFT, and FLUFFY. So fluffy that one poke makes me feel as though I’ve ouched clouds and honestly I think just from your cheeks alone I now know what clouds feel like." },
  { id: 58, category: "pink", message: "I love your smile and how cheeky and gummy they are. How whenever I smile, you’ll return a 10 times more bigger and brighter, how when you smile, you don’t smile with just your mouth but with your eyes as well. It may just be a typical asian thing but nonetheless I grew up with people telling me I smile too big and that my eyes shouldn’t be like that when I smile, but I think for a smile to be truly genuine, it reaches all the way up to the eyes and the entire face lights up and with you it’s exactly that, and I love it." },
  { id: 59, category: "blue", message: "I love your scent and how I can never get enough of it, one sniff of you and I think I’ve walked into a garden, a garden I never wanna leave. I don’t know if I told you this but, after being with you I continuously smell my afterwards. All the way on the drive home my hands are cuffed to my nose, trying to savour every whiff. How afterwards I try as long as I can to go without washing my hands. Really, if I could I’d stuff you up into a perfume bottle and keep you forever." },
  { id: 60, category: "yellow", message: "I love your hands and how they fit so perfectly with mine and how whenever I reach out for them, they always meet me halfway. How they feel so soft, smooth, and tender in mine, how they’re so delicate and precious. Every single part fits so wonderfully." },
  { id: 61, category: "pink", message: "I love how you make me feel safe enough to be childish and carefree. How you bring out the inner child in me and how refreshing it feels to have the weight of being a mature individual be lifted off." },
  { id: 62, category: "blue", message: "I love who you are as a person. How you’re so confident in yourself. How you’re just an amazing person through and through, I love all of it." }
];
  const msgList = messages[category];
  return {
    id: i + 1,
    category,
    message: msgList[i % msgList.length]
  };
});

